manager:
  private_ip: {{ node.private_ip_address }}
  public_ip: {{ node.ip_address }}
  {% if node.hostname-%}
  hostname: {{ node.hostname }}
  {%-endif %}

postgresql_server:
  cert_path: {{ node.cert_path }}
  key_path: {{ node.key_path }}
  ca_path: {{ ca_path }}

  ssl_client_verification: true
  ssl_only_connections: true

  postgres_password: strongpostgresqlpassword
  cluster:
    nodes: {{ postgresql_cluster }}

    etcd:
      cluster_token: strongetcdclustertoken
      root_password: strongetcdrootpassword
      patroni_password: strongpatronipassword
    patroni:
      rest_password: strongrestpassword
    postgres:
      replicator_password: strongreplicatorpassword

prometheus:
  credentials:
    username: prometheus_user
    password: strongprometheuspassword

  cert_path: {{ node.cert_path }}
  key_path: {{ node.key_path }}
  ca_path: {{ ca_path }}

validations:
  minimum_required_total_physical_memory_in_mb: 1024

services_to_install:
  - database_service
  - monitoring_service
